# config file for {{ cookiecutter.pipeline_name }} pipeline

general_settings:
        result_dir: "results/"
        notebook_dir: "notebooks/"

rules:
        {%- for rule in cookiecutter.context.rules %}
        {{ rule.name }}:
                execute_runs:
                        - all
                default_params: 
                        {%- for pname, fname in rule.keywords['input'].items() %}
                        {{ pname }}: {{ fname }}
                        {%- endfor %}
                        {%- for pname, val in rule.keywords['params'].items() %}
                        {{ pname }}: {{ val }}
                        {%- endfor %}
        {%- endfor %}


runs:
        all: {}
