# config file for {{ cookiecutter.pipeline_name }} pipeline

general_settings:
        result_dir: "results_{runID}/"
        notebook_dir: "notebooks_{runID}/"
        execute_runs: &exec_runs
                - all

rules:
        {%- for rule in cookiecutter.context.rules %}
        {{ rule.name }}:
                execute_in_runs: *exec_runs
                default_params: 
                        {%- if 'input' in rule.keywords %}
                        {%- for pname, fname in rule.keywords['input'].items() %}
                        input_{{ pname }}: "{{ 'results_{runID}/' if not fname.lstrip('"')|first == '/' }}{{ fname.lstrip('"').rstrip('"') }}"
                        {%- endfor %}
                        {%- endif %}
                        {%- if 'params' in rule.keywords %}
                        {%- for pname, val in rule.keywords['params'].items() %}
                        {{ pname }}: {{ val }}
                        {%- endfor %}
                        {%- endif %}
        {%- endfor %}


runs:
        all: {}
